# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'survivor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for survivor
  pod 'CocoaLumberjack', '~> 3.3.0'
  pod 'Starscream', '~> 3.0.2'
  pod 'Decodable', '~> 0.6.0'

  target 'survivorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
